# Size of the universe
universeSize:
  maxGalaxies: 3
  maxSystems: 3
  maxPlanets: 3

# Starter planet settings
starterPlanet:
  # Starting resources
  resources:
    crystal: 200
    gas: 100
    energy: 800

# New planet settings
newPlanet:
  resources:
    crystal: 100
    gas: 50
    energy: 400

# Round time in seconds
roundTime: 1