RESTwars webservice documentation
=================================

Authentication
--------------

Some endpoints need authentication. Authentication is done via HTTP Basic Auth.

Players
-------

Create a new player
~~~~~~~~~~~~~~~~~~~

Creates a new player.

URL: `POST /v1/player`

Request:

[source,json]
include::requests/create-player.json[]

This creates a new player with username "player1" and password "s3cret".

Response:

* `201 Created` if the player has been created.
* `409 Conflict` if the username is already taken.

Fights
------

List fights
~~~~~~~~~~~

Lists all fights where the player is either attacker or defender. Needs authentication.

URL: `GET /v1/player/fight`

Response:

[source,json]
include::responses/fights.json[]

Fight on planet 1.2.3 between "player1" and "player2". "player1" sent 3 mosquitoes and 2 mules, but all were destroyed. "player2" defended with 5 mosquitoes and 1 colony ship, from which 1 mosquito and 1 colony ship survived.

List fights with a planet
~~~~~~~~~~~~~~~~~~~~~~~~~

Lists all fights with a planet. Needs authentication.

URL: `GET /v1/planet/:location/fight`

Response:

[source,json]
include::responses/fights.json[]

Fight on planet 1.2.3 between "player1" and "player2". "player1" sent 3 mosquitoes and 2 mules, but all were destroyed. "player2" defended with 5 mosquitoes and 1 colony ship, from which 1 mosquito and 1 colony ship survived.

Planets
-------

List planets
~~~~~~~~~~~~

Lists all planets of the player. Needs authentication.

URL: `GET /v1/planet`

Response:

[source,json]
include::responses/list-planets.json[]

The player has a planet at 1.2.3 with 100 crystals, 50 gas and 400 energy. Another planet of the player is at 2.3.4, with 200 crystals, 100 gas and 800 energy.

Scan with telescope
~~~~~~~~~~~~~~~~~~~

Returns a list of all planets and their owners in the vicinity. Needs authentication.

URL: `GET /v1/planet/:location/telescope/scan`

Response:

[source,json]
include::responses/telescope-scan.json[]

Planet 1.1.1 and 1.1.3 is owned by "player1", planet 1.1.2 is owned by "player2".

General information
-------------------

Application information
~~~~~~~~~~~~~~~~~~~~~~~

Returns information about the RESTwars application.

URL: `GET /v1/restwars`

Response:

[source,json]
include::responses/application-information.json[]

RESTwars is running in version 1.0.0 and has been built from the commit hash "e1d9d75d436a4adaca8d0fd56f5c13550e95e797".

RESTwars configuration
~~~~~~~~~~~~~~~~~~~~~~

Returns information about the RESTwars configuration.

URL: `GET /v1/configuration`

Response:

[source,json]
include::responses/configuration.json[]

A round lasts 30 seconds.

Round information
-----------------

Round information
~~~~~~~~~~~~~~~~~

Returns information about the round.

URL: `GET /v1/round`

Response:

[source,json]
include::responses/round-information.json[]

The game is currently in round 13 and each round lasts 30 seconds.

Round websocket
~~~~~~~~~~~~~~~

Provides a websocket which notifies the client when a new round starts.

URL: `/v1/round/websocket`

Response:

[source,json]
include::responses/round-websocket.json[]

The game is currently in round 17.

Buildings
---------

List buildings
~~~~~~~~~~~~~~

Lists buildings on a planet. Needs authentication.

URL: `GET /v1/planet/:location/building`

Response:

[source,json]
include::responses/list-buildings.json[]

A command center level 2 and a crystal mine level 3 exists on the planet.

Construct building
~~~~~~~~~~~~~~~~~~

Builds a new building on a planet. Needs authentication.

URL: `POST /v1/planet/:location/building`

Request:

[source,json]
include::requests/construct-building.json[]

Constructs a new command center.

Response:

* `201 Created`
[source,json]
include::responses/construct-building.json[]

The new command center will have level 2 and is done in round 102.

* `400 Bad Request` if not enough build slots are available
* `400 Bad Request` if not enough resources are available
* `400 Bad Request` if a building of the same type is already under construction

List construction sites
~~~~~~~~~~~~~~~~~~~~~~~

Lists construction sites on a planet. Needs authentication.

URL: `GET /v1/planet/:location/construction-site`

Response:

[source,json]
include::responses/list-construction-sites.json[]

A command center level 2 is being built. It's done in round 102.

Ships
-----

List ships in hangar
~~~~~~~~~~~~~~~~~~~~

Lists ships in the hangar on a planet. Needs authentication.

URL: `GET /v1/planet/:location/hangar`

Response:

[source,json]
include::responses/ships-in-hangar.json[]

The hangar contains 3 mosquitoes and 2 colony ships.

Construct ship
~~~~~~~~~~~~~~

Constructs a new ship on a planet. Needs authentication.

URL: `POST /v1/planet/:location/hangar`

Request:

[source,json]
include::requests/construct-ship.json[]

Builds a new mosquito.

Ships available for construction are:

[options="header"]
|=================
|Ship     |Attack|Defense|Cargo Space|Speed|Flight Cost Modifier|Build Time (Rounds)|Build Cost (Crystal/Gas/Energy)
|MOSQUITO |14    |10     |10         |1    |1                   |10                 |100/20/270
|COLONY   |0     |75     |500        |0.5  |2                   |60                 |350/150/1750
|MULE     |0     |50     |750        |1    |1.5                 |20                 |350/150/1750
|================

Response:

* `201 Created`
[source,json]
include::responses/construct-ship.json[]

The new mosquito is done in round 73.

* `400 Bad Request` if not enough build slots are available
* `400 Bad Request` if not enough resources are available

List ships in construction
~~~~~~~~~~~~~~~~~~~~~~~~~~

Lists all ships in construction on a planet. Needs authentication.

URL: `GET /v1/planet/:location/shipyard`

Response:

[source,json]
include::responses/ships-in-construction.json[]

A colony ship is done in round 55.

Flights
-------

Start a flight
~~~~~~~~~~~~~~

Starts a new flight from a planet. Needs authentication.

URL: `POST /v1/planet/:location/flight`

Request:

[source,json]
include::requests/start-flight.json[]

Starts a colonize flight to planet 1.2.3 with 5 mosquitoes and 1 colony ship. Cargo consists of 100 crystals and 50 gas.

You can specify the following flight types:

* `ATTACK`: Attack (and loot) an enemy planet. Ships not lost in the fight will return with stolen ressources.
* `COLONIZE`: Colonize an empty planet. The colony ship will be converted to a command center, the other ships will remain at the target planet. The ships for the flight must contain at least one colony ship.
* `TRANSFER`: Transfer the ships to another planet (must be owned). The ships will remain at the target planet.
* `TRANSPORT`: Transport cargo to another planet (must be owned). After the cargo has been unloaded, the sent ships will return. Only crystal and gas can be transported. Energy cannot be transported.

The flight started from 1.2.3 and is a colonize flight to 4.5.6. The flight will arrive in round 112 and consists of 3 mosquitoes and 2 colony ships.

If ships in a flight order have different speed values, all ships flight with the speed of the slowest ship.

Response:

* `200 OK`

[source,json]
include::responses/start-flight.json[]

The flight started from 1.2.3 and is a colonize flight to 4.5.6. The flight will arrive in round 112 and consists of 3 mosquitoes and 2 colony ships.

* `400 Bad Request` if start and destination are the same.
* `400 Bad Request` if the location is invalid (e.g. not in the universe).
* `400 Bad Request` if no ships are on the flight.
* `400 Bad Request` if the flight is a colonize flight and no colony ship is on the flight.
* `400 Bad Request` if the flight is an attack flight and resources are in the cargo.
* `400 Bad Request` if energy is in the cargo.
* `400 Bad Request` if not enough cargo space is available.
* `400 Bad Request` if not enough resources are available to start the flight.
* `400 Bad Request` if not enough ships are available.

List all flights
~~~~~~~~~~~~~~~~

Lists all flights for the player. Needs authentication.

URL: `GET v1/flight`

Response:

[source,json]
include::responses/flights.json[]

List all flights with destination
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Lists all flights with a given destination. Needs authentication.

URL: `GET v1/flight/to/:location`

Response:

[source,json]
include::responses/flights.json[]

List all flights with start
~~~~~~~~~~~~~~~~~~~~~~~~~~~

Lists all flights with a given start. Needs authentication.

URL: `GET v1/flight/from/:location`

Response:

[source,json]
include::responses/flights.json[]

Attack mechanics
~~~~~~~~~~~~~~~~

When a planet is attacked, all ships residing at the planet automatically defend.

To ensure a fair fight, the calculation is being done in two steps:

1. The attack points of the attacking ships are accumulated. One by one, random defending ships which have less or equal defense points than the cumulated attack points of the defending ships are marked for destruction and taken out of the fight and their defense value is subtracted from the cumulated attack points. This process is repeated until there are either no more defending ships or the remaining attack value of the attacking ships is no longer sufficient to destroy a ship.

2. The same process is now carried out in reverse. All defending ships initially present on the attacked planet are now attacking the assailants ships.

Finally, all attacking and defending ships which were marked for destruction or being destroyed. If there are remaining attacker ships, they will now loot the planet. They will therefore take at most an amount equal to half their available cargo size of crystal and gas each. They can not take more than what is available on the planet at the beginning of the fight.
