RESTwars webservice documentation
=================================

Authentication
--------------

Some endpoints need authentication. Authentication is done via HTTP Basic Auth.

Create a new player
-------------------

Creates a new player.

URL: `POST /v1/player`

Request:

[source,json]
include::requests/create-player.json[]

Response:

`201 Created` if the player has been created.

List planets
------------

Lists all planets of the player. Needs authentication.

URL: `GET /v1/planet`

Response:

[source,json]
include::responses/list-planets.json[]

Application information
-----------------------

Returns information about the RESTwars application.

URL: `GET /v1/restwars`

Response:

[source,json]
include::responses/application-information.json[]


RESTwars configuration
----------------------

Returns information about the RESTwars configuration.

URL: `GET /v1/configuration`

Response:

[source,json]
include::responses/configuration.json[]


Round information
-----------------

Returns information about the round.

URL: `GET /v1/round`

Response:

[source,json]
include::responses/round-information.json[]


Round websocket
---------------

Provides a websocket which notifies the client when a new round starts.

URL: `/v1/round/websocket`

Response:

[source,json]
include::responses/round-websocket.json[]

List buildings
--------------

Lists buildings on a planet. Needs authentication.

URL: `GET /v1/planet/:location/building`

Response:

[source,json]
include::responses/list-buildings.json[]

Construct building
------------------

Builds a new building on a planet. Needs authentication.

URL: `POST /v1/planet/:location/building`

Request:

[source,json]
include::requests/construct-building.json[]

Response:

[source,json]
include::responses/construct-building.json[]

List construction sites
-----------------------

Lists construction sites on a planet. Needs authentication.

URL: `GET /v1/planet/:location/construction-site`

Response:

[source,json]
include::responses/list-construction-sites.json[]

List ships in hangar
--------------------

Lists ships in the hangar on a planet. Needs authentication.

URL: `GET /v1/planet/:location/hangar`

Response:

[source,json]
include::responses/ships-in-hangar.json[]

Construct ship
--------------

Constructs a new ship on a planet. Needs authentication.

URL: `POST /v1/planet/:location/hangar`

Request:

[source,json]
include::requests/construct-ship.json[]

Response:

[source,json]
include::responses/construct-ship.json[]

List ships in construction
--------------------------

Lists all ships in construction on a planet. Needs authentication.

URL: `GET /v1/planet/:location/shipyard`

Response:

[source,json]
include::responses/ships-in-construction.json[]

Start a flight
--------------

Starts a new flight from a planet. Needs authentication.

URL: `POST /v1/planet/:location/flight`

Request:

[source,json]
include::requests/start-flight.json[]

Response:

[source,json]
include::responses/start-flight.json[]

Scan with telescope
-------------------

Returns a list of all planets and their owners in the vicinity.

URL: `GET /v1/planet/:location/telescope/scan`

Response:

[source,json]
include::responses/telescope-scan.json[]