# Building properties
 buildingsProperties:
   commandCenterProperties:
     buildTime:
       baseTime: 50
       gainPerLevel: 25
     buildCost:
       baseCost:
         crystal: 200
         gas: 100
         energy: 800
       gainPerLevel:
         crystal: 100
         gas: 50
         energy: 400
   crystalMineProperties:
     buildTime:
       baseTime: 30
       gainPerLevel: 10
     buildCost:
       baseCost:
         crystal: 100
         gas: 50
         energy: 400
       gainPerLevel:
         crystal: 50
         gas: 25
         energy: 200
   gasRefineryProperties:
     buildTime:
       baseTime: 30
       gainPerLevel: 10
     buildCost:
       baseCost:
         crystal: 100
         gas: 50
         energy: 400
       gainPerLevel:
         crystal: 50
         gas: 25
         energy: 200
   solarPanelsProperties:
     buildTime:
       baseTime: 30
       gainPerLevel: 10
     buildCost:
       baseCost:
         crystal: 100
         gas: 50
         energy: 400
       gainPerLevel:
         crystal: 50
         gas: 25
         energy: 200
   telescopeProperties:
     buildTime:
       baseTime: 50
       gainPerLevel: 10
     buildCost:
       baseCost:
         crystal: 100
         gas: 50
         energy: 400
       gainPerLevel:
         crystal: 50
         gas: 25
         energy: 200
   shipyardProperties:
     buildTime:
       baseTime: 100
       gainPerLevel: 50
     buildCost:
       baseCost:
         crystal: 300
         gas: 150
         energy: 1200
       gainPerLevel:
         crystal: 150
         gas: 75
         energy: 600
  buildTimeAttenuation: 0.05

shipsProperties:
  mosquitoProperties:
    buildTime: 10
    buildCost:
      crystal: 100
      gas: 20
      energy: 270
    flightSpeed: 1.0
    flightCost: 1.0
    attackPoints: 14
    defendPoints: 10
    cargoSpace: 10
  colonyProperties:
    buildTime: 60
    buildCost:
      crystal: 350
      gas: 150
      energy: 270
    flightSpeed: 0.5
    flightCost: 2.0
    attackPoints: 0
    defendPoints: 75
    cargoSpace: 500
  muleProperties:
    buildTime: 20
    buildCost:
      crystal: 200
      gas: 100
      energy: 1225
    flightSpeed: 1.0
    flightCost: 1.5
    attackPoints: 0
    defendPoints: 20
    cargoSpace: 750
  buildTimeAttenuation: 0.05

scoringProperties:
  crystalMultiplier: 4L
  gasMultiplier: 8L
