# Size of the universe
universeSize:
  maxGalaxies: 4
  maxSystems: 4
  maxPlanets: 4

# Starter planet settings
starterPlanet:
  # Starting resources
  resources:
    crystal: 200
    gas: 100
    energy: 800

# New planet settings
newPlanet:
  resources:
    crystal: 100
    gas: 50
    energy: 400

# Round time in seconds
roundTime: 1

# Calculate points every X rounds
calculatePointsEvery: 50

# Admin access
admin:
  username: admin
  password: admin

# Database configuration
database:
  # In-memory database:
  # url: jdbc:h2:mem:restwars
  url: jdbc:h2:./data/restwars-tournament
  driver: org.h2.Driver
  dialect: H2
  username: ''
  password: ''
