/**
 * This class is generated by jOOQ
 */
package restwars.storage.jooq;


import restwars.storage.jooq.tables.Planets;
import restwars.storage.jooq.tables.Players;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

	/**
	 * The table PUBLIC.PLAYERS
	 */
	public static final Players PLAYERS = restwars.storage.jooq.tables.Players.PLAYERS;

	/**
	 * The table PUBLIC.PLANETS
	 */
	public static final Planets PLANETS = restwars.storage.jooq.tables.Planets.PLANETS;
}
