/**
 * This class is generated by jOOQ
 */
package restwars.storage.jooq;


import restwars.storage.jooq.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

	/**
	 * The table PUBLIC.PLAYERS
	 */
	public static final Players PLAYERS = restwars.storage.jooq.tables.Players.PLAYERS;

	/**
	 * The table PUBLIC.PLANETS
	 */
	public static final Planets PLANETS = restwars.storage.jooq.tables.Planets.PLANETS;

	/**
	 * The table PUBLIC.BUILDINGS
	 */
	public static final Buildings BUILDINGS = restwars.storage.jooq.tables.Buildings.BUILDINGS;

	/**
	 * The table PUBLIC.CONSTRUCTION_SITES
	 */
	public static final ConstructionSites CONSTRUCTION_SITES = restwars.storage.jooq.tables.ConstructionSites.CONSTRUCTION_SITES;

	/**
	 * The table PUBLIC.ROUND
	 */
	public static final Round ROUND = restwars.storage.jooq.tables.Round.ROUND;

	/**
	 * The table PUBLIC.SHIPS_IN_CONSTRUCTION
	 */
	public static final ShipsInConstruction SHIPS_IN_CONSTRUCTION = restwars.storage.jooq.tables.ShipsInConstruction.SHIPS_IN_CONSTRUCTION;

	/**
	 * The table PUBLIC.POINTS
	 */
	public static final Points POINTS = restwars.storage.jooq.tables.Points.POINTS;

	/**
	 * The table PUBLIC.EVENTS
	 */
	public static final Events EVENTS = restwars.storage.jooq.tables.Events.EVENTS;
}
