/**
 * This class is generated by jOOQ
 */
package restwars.storage.jooq.tables;


import org.jooq.*;
import org.jooq.impl.TableImpl;
import restwars.storage.jooq.Keys;
import restwars.storage.jooq.Public;
import restwars.storage.jooq.tables.records.HangarRecord;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Hangar extends TableImpl<HangarRecord> {

	private static final long serialVersionUID = 1138979815;

	/**
	 * The reference instance of <code>PUBLIC.HANGAR</code>
	 */
	public static final Hangar HANGAR = new Hangar();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<HangarRecord> getRecordType() {
		return HangarRecord.class;
	}

	/**
	 * The column <code>PUBLIC.HANGAR.ID</code>.
	 */
	public final TableField<HangarRecord, UUID> ID = createField("ID", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>PUBLIC.HANGAR.PLANET_ID</code>.
	 */
	public final TableField<HangarRecord, UUID> PLANET_ID = createField("PLANET_ID", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * Create a <code>PUBLIC.HANGAR</code> table reference
	 */
	public Hangar() {
		this("HANGAR", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.HANGAR</code> table reference
	 */
	public Hangar(String alias) {
		this(alias, HANGAR);
	}

	private Hangar(String alias, Table<HangarRecord> aliased) {
		this(alias, aliased, null);
	}

	private Hangar(String alias, Table<HangarRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<HangarRecord> getPrimaryKey() {
		return Keys.CONSTRAINT_7E9;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<HangarRecord>> getKeys() {
		return Arrays.<UniqueKey<HangarRecord>>asList(Keys.CONSTRAINT_7E9, Keys.CONSTRAINT_7E95);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<HangarRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<HangarRecord, ?>>asList(Keys.CONSTRAINT_7E956);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Hangar as(String alias) {
		return new Hangar(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Hangar rename(String name) {
		return new Hangar(name, null);
	}
}
