/*
 * This file is generated by jOOQ.
*/
package restwars.storage.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import restwars.storage.jooq.tables.Events;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record5<UUID, String, Long, UUID, UUID> {

    private static final long serialVersionUID = -780806028;

    /**
     * Setter for <code>PUBLIC.EVENTS.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENTS.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PUBLIC.EVENTS.TYPE</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENTS.TYPE</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.EVENTS.ROUND</code>.
     */
    public void setRound(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENTS.ROUND</code>.
     */
    public Long getRound() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>PUBLIC.EVENTS.PLAYER_ID</code>.
     */
    public void setPlayerId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENTS.PLAYER_ID</code>.
     */
    public UUID getPlayerId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>PUBLIC.EVENTS.PLANET_ID</code>.
     */
    public void setPlanetId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.EVENTS.PLANET_ID</code>.
     */
    public UUID getPlanetId() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, String, Long, UUID, UUID> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, String, Long, UUID, UUID> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Events.EVENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Events.EVENTS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Events.EVENTS.ROUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Events.EVENTS.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field5() {
        return Events.EVENTS.PLANET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getRound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value5() {
        return getPlanetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value2(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value3(Long value) {
        setRound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value4(UUID value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value5(UUID value) {
        setPlanetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord values(UUID value1, String value2, Long value3, UUID value4, UUID value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(UUID id, String type, Long round, UUID playerId, UUID planetId) {
        super(Events.EVENTS);

        set(0, id);
        set(1, type);
        set(2, round);
        set(3, playerId);
        set(4, planetId);
    }
}
