/*
 * This file is generated by jOOQ.
*/
package restwars.storage.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import restwars.storage.jooq.tables.Fights;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.9.0"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FightsRecord extends UpdatableRecordImpl<FightsRecord> implements Record7<UUID, UUID, UUID, UUID, Long, Integer, Integer> {

    private static final long serialVersionUID = -1260565231;

    /**
     * Setter for <code>PUBLIC.FIGHTS.ID</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.ID</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>PUBLIC.FIGHTS.ATTACKER_ID</code>.
     */
    public void setAttackerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.ATTACKER_ID</code>.
     */
    public UUID getAttackerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>PUBLIC.FIGHTS.DEFENDER_ID</code>.
     */
    public void setDefenderId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.DEFENDER_ID</code>.
     */
    public UUID getDefenderId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>PUBLIC.FIGHTS.PLANET_ID</code>.
     */
    public void setPlanetId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.PLANET_ID</code>.
     */
    public UUID getPlanetId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>PUBLIC.FIGHTS.ROUND</code>.
     */
    public void setRound(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.ROUND</code>.
     */
    public Long getRound() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>PUBLIC.FIGHTS.LOOT_CRYSTAL</code>.
     */
    public void setLootCrystal(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.LOOT_CRYSTAL</code>.
     */
    public Integer getLootCrystal() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>PUBLIC.FIGHTS.LOOT_GAS</code>.
     */
    public void setLootGas(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.FIGHTS.LOOT_GAS</code>.
     */
    public Integer getLootGas() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, UUID, UUID, UUID, Long, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<UUID, UUID, UUID, UUID, Long, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Fights.FIGHTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Fights.FIGHTS.ATTACKER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field3() {
        return Fights.FIGHTS.DEFENDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return Fights.FIGHTS.PLANET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Fights.FIGHTS.ROUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Fights.FIGHTS.LOOT_CRYSTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Fights.FIGHTS.LOOT_GAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getAttackerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value3() {
        return getDefenderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getPlanetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getRound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getLootCrystal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getLootGas();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value2(UUID value) {
        setAttackerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value3(UUID value) {
        setDefenderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value4(UUID value) {
        setPlanetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value5(Long value) {
        setRound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value6(Integer value) {
        setLootCrystal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord value7(Integer value) {
        setLootGas(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FightsRecord values(UUID value1, UUID value2, UUID value3, UUID value4, Long value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FightsRecord
     */
    public FightsRecord() {
        super(Fights.FIGHTS);
    }

    /**
     * Create a detached, initialised FightsRecord
     */
    public FightsRecord(UUID id, UUID attackerId, UUID defenderId, UUID planetId, Long round, Integer lootCrystal, Integer lootGas) {
        super(Fights.FIGHTS);

        set(0, id);
        set(1, attackerId);
        set(2, defenderId);
        set(3, planetId);
        set(4, round);
        set(5, lootCrystal);
        set(6, lootGas);
    }
}
