/**
 * This class is generated by jOOQ
 */
package restwars.storage.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import restwars.storage.jooq.tables.Flights;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FlightsRecord extends UpdatableRecordImpl<FlightsRecord> implements Record15<UUID, UUID, Integer, Integer, Integer, Integer, Integer, Integer, Long, String, String, Integer, Integer, Boolean, Double> {

    private static final long serialVersionUID = -347315783;

    /**
     * Setter for <code>PUBLIC.FLIGHTS.ID</code>.
     */
    public void setId(UUID value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.ID</code>.
     */
    public UUID getId() {
        return (UUID) getValue(0);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.PLAYER_ID</code>.
     */
    public void setPlayerId(UUID value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.PLAYER_ID</code>.
     */
    public UUID getPlayerId() {
        return (UUID) getValue(1);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.START_GALAXY</code>.
     */
    public void setStartGalaxy(Integer value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.START_GALAXY</code>.
     */
    public Integer getStartGalaxy() {
        return (Integer) getValue(2);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.START_SYSTEM</code>.
     */
    public void setStartSystem(Integer value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.START_SYSTEM</code>.
     */
    public Integer getStartSystem() {
        return (Integer) getValue(3);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.START_PLANET</code>.
     */
    public void setStartPlanet(Integer value) {
        setValue(4, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.START_PLANET</code>.
     */
    public Integer getStartPlanet() {
        return (Integer) getValue(4);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.DESTINATION_GALAXY</code>.
     */
    public void setDestinationGalaxy(Integer value) {
        setValue(5, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.DESTINATION_GALAXY</code>.
     */
    public Integer getDestinationGalaxy() {
        return (Integer) getValue(5);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.DESTINATION_SYSTEM</code>.
     */
    public void setDestinationSystem(Integer value) {
        setValue(6, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.DESTINATION_SYSTEM</code>.
     */
    public Integer getDestinationSystem() {
        return (Integer) getValue(6);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.DESTINATION_PLANET</code>.
     */
    public void setDestinationPlanet(Integer value) {
        setValue(7, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.DESTINATION_PLANET</code>.
     */
    public Integer getDestinationPlanet() {
        return (Integer) getValue(7);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.STARTED_IN_ROUND</code>.
     */
    public void setStartedInRound(Long value) {
        setValue(8, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.STARTED_IN_ROUND</code>.
     */
    public Long getStartedInRound() {
        return (Long) getValue(8);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.DIRECTION</code>.
     */
    public void setDirection(String value) {
        setValue(9, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.DIRECTION</code>.
     */
    public String getDirection() {
        return (String) getValue(9);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.TYPE</code>.
     */
    public void setType(String value) {
        setValue(10, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.TYPE</code>.
     */
    public String getType() {
        return (String) getValue(10);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.CARGO_CRYSTAL</code>.
     */
    public void setCargoCrystal(Integer value) {
        setValue(11, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.CARGO_CRYSTAL</code>.
     */
    public Integer getCargoCrystal() {
        return (Integer) getValue(11);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.CARGO_GAS</code>.
     */
    public void setCargoGas(Integer value) {
        setValue(12, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.CARGO_GAS</code>.
     */
    public Integer getCargoGas() {
        return (Integer) getValue(12);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.DETECTED</code>.
     */
    public void setDetected(Boolean value) {
        setValue(13, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.DETECTED</code>.
     */
    public Boolean getDetected() {
        return (Boolean) getValue(13);
    }

    /**
     * Setter for <code>PUBLIC.FLIGHTS.SPEED</code>.
     */
    public void setSpeed(Double value) {
        setValue(14, value);
    }

    /**
     * Getter for <code>PUBLIC.FLIGHTS.SPEED</code>.
     */
    public Double getSpeed() {
        return (Double) getValue(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UUID, UUID, Integer, Integer, Integer, Integer, Integer, Integer, Long, String, String, Integer, Integer, Boolean, Double> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<UUID, UUID, Integer, Integer, Integer, Integer, Integer, Integer, Long, String, String, Integer, Integer, Boolean, Double> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Flights.FLIGHTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return Flights.FLIGHTS.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Flights.FLIGHTS.START_GALAXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Flights.FLIGHTS.START_SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Flights.FLIGHTS.START_PLANET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Flights.FLIGHTS.DESTINATION_GALAXY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Flights.FLIGHTS.DESTINATION_SYSTEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Flights.FLIGHTS.DESTINATION_PLANET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Flights.FLIGHTS.STARTED_IN_ROUND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Flights.FLIGHTS.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Flights.FLIGHTS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Flights.FLIGHTS.CARGO_CRYSTAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Flights.FLIGHTS.CARGO_GAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field14() {
        return Flights.FLIGHTS.DETECTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field15() {
        return Flights.FLIGHTS.SPEED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStartGalaxy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getStartSystem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getStartPlanet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getDestinationGalaxy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDestinationSystem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDestinationPlanet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getStartedInRound();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getCargoCrystal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getCargoGas();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value14() {
        return getDetected();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value15() {
        return getSpeed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value2(UUID value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value3(Integer value) {
        setStartGalaxy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value4(Integer value) {
        setStartSystem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value5(Integer value) {
        setStartPlanet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value6(Integer value) {
        setDestinationGalaxy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value7(Integer value) {
        setDestinationSystem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value8(Integer value) {
        setDestinationPlanet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value9(Long value) {
        setStartedInRound(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value10(String value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value11(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value12(Integer value) {
        setCargoCrystal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value13(Integer value) {
        setCargoGas(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value14(Boolean value) {
        setDetected(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord value15(Double value) {
        setSpeed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FlightsRecord values(UUID value1, UUID value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Long value9, String value10, String value11, Integer value12, Integer value13, Boolean value14, Double value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlightsRecord
     */
    public FlightsRecord() {
        super(Flights.FLIGHTS);
    }

    /**
     * Create a detached, initialised FlightsRecord
     */
    public FlightsRecord(UUID id, UUID playerId, Integer startGalaxy, Integer startSystem, Integer startPlanet, Integer destinationGalaxy, Integer destinationSystem, Integer destinationPlanet, Long startedInRound, String direction, String type, Integer cargoCrystal, Integer cargoGas, Boolean detected, Double speed) {
        super(Flights.FLIGHTS);

        setValue(0, id);
        setValue(1, playerId);
        setValue(2, startGalaxy);
        setValue(3, startSystem);
        setValue(4, startPlanet);
        setValue(5, destinationGalaxy);
        setValue(6, destinationSystem);
        setValue(7, destinationPlanet);
        setValue(8, startedInRound);
        setValue(9, direction);
        setValue(10, type);
        setValue(11, cargoCrystal);
        setValue(12, cargoGas);
        setValue(13, detected);
        setValue(14, speed);
    }
}
