/**
 * This class is generated by jOOQ
 */
package restwars.storage.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;
import restwars.storage.jooq.tables.Round;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
		value = {
				"http://www.jooq.org",
				"jOOQ version:3.7.3"
		},
		comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RoundRecord extends TableRecordImpl<RoundRecord> implements Record1<Long> {

	private static final long serialVersionUID = -1135524539;

	/**
	 * Setter for <code>PUBLIC.ROUND.ROUND</code>.
	 */
	public void setRound(Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>PUBLIC.ROUND.ROUND</code>.
	 */
	public Long getRound() {
		return (Long) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Long> fieldsRow() {
		return (Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row1<Long> valuesRow() {
		return (Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field1() {
		return Round.ROUND.ROUND_;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value1() {
		return getRound();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoundRecord value1(Long value) {
		setRound(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoundRecord values(Long value1) {
		value1(value1);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoundRecord
	 */
	public RoundRecord() {
		super(Round.ROUND);
	}

	/**
	 * Create a detached, initialised RoundRecord
	 */
	public RoundRecord(Long round) {
		super(Round.ROUND);

		setValue(0, round);
	}
}
