/**
 * This class is generated by jOOQ
 */
package restwars.storage.jooq.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import restwars.storage.jooq.tables.ShipsInConstruction;

import javax.annotation.Generated;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.7.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ShipsInConstructionRecord extends UpdatableRecordImpl<ShipsInConstructionRecord> implements Record4<UUID, UUID, String, Long> {

    private static final long serialVersionUID = -912916237;

    /**
     * Setter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.ID</code>.
     */
    public void setId(UUID value) {
        setValue(0, value);
    }

    /**
     * Getter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.ID</code>.
     */
    public UUID getId() {
        return (UUID) getValue(0);
    }

    /**
     * Setter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.PLANET_ID</code>.
     */
    public void setPlanetId(UUID value) {
        setValue(1, value);
    }

    /**
     * Getter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.PLANET_ID</code>.
     */
    public UUID getPlanetId() {
        return (UUID) getValue(1);
    }

    /**
     * Setter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.TYPE</code>.
     */
    public void setType(String value) {
        setValue(2, value);
    }

    /**
     * Getter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.TYPE</code>.
     */
    public String getType() {
        return (String) getValue(2);
    }

    /**
     * Setter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.DONE</code>.
     */
    public void setDone(Long value) {
        setValue(3, value);
    }

    /**
     * Getter for <code>PUBLIC.SHIPS_IN_CONSTRUCTION.DONE</code>.
     */
    public Long getDone() {
        return (Long) getValue(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UUID, UUID, String, Long> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UUID, UUID, String, Long> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return ShipsInConstruction.SHIPS_IN_CONSTRUCTION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return ShipsInConstruction.SHIPS_IN_CONSTRUCTION.PLANET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ShipsInConstruction.SHIPS_IN_CONSTRUCTION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return ShipsInConstruction.SHIPS_IN_CONSTRUCTION.DONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPlanetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShipsInConstructionRecord value1(UUID value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShipsInConstructionRecord value2(UUID value) {
        setPlanetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShipsInConstructionRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShipsInConstructionRecord value4(Long value) {
        setDone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ShipsInConstructionRecord values(UUID value1, UUID value2, String value3, Long value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShipsInConstructionRecord
     */
    public ShipsInConstructionRecord() {
        super(ShipsInConstruction.SHIPS_IN_CONSTRUCTION);
    }

    /**
     * Create a detached, initialised ShipsInConstructionRecord
     */
    public ShipsInConstructionRecord(UUID id, UUID planetId, String type, Long done) {
        super(ShipsInConstruction.SHIPS_IN_CONSTRUCTION);

        setValue(0, id);
        setValue(1, planetId);
        setValue(2, type);
        setValue(3, done);
    }
}
